# Generated by Django 2.2.7 on 2021-05-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_partsframe_ponics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('variety', models.CharField(max_length=255, verbose_name='Сорт')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('col', models.CharField(max_length=255, verbose_name='Количество семян в упаковке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Ponics',
            new_name='Ponic',
        ),
        migrations.DeleteModel(
            name='PartsFrame',
        ),
    ]
