# Generated by Django 2.2.7 on 2021-05-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210514_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='name',
        ),
    ]
